name: child_safety_monitor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.14.0
  path_provider: ^2.0.0
  path: ^1.8.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.65.0
  uuid: ^4.2.1
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.14.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

